<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

        function generateRandomBytes($length,$cryptographicallyStrong=true)
        {
                $bytes='';
                if(function_exists('openssl_random_pseudo_bytes'))
                {
                        $bytes=openssl_random_pseudo_bytes($length,$strong);
                        if(strlen($bytes)>=$length)
                                return substr($bytes,0,$length);
                }

                if(function_exists('mcrypt_create_iv') &&
                        ($bytes=mcrypt_create_iv($length, MCRYPT_DEV_URANDOM))!==false &&
                        strlen($bytes)>=$length)
                {
                        return substr($bytes,0,$length);
                }

                if(($file=@fopen('/dev/urandom','rb'))!==false &&
                        ($bytes=@fread($file,$length))!==false &&
                        (fclose($file) || true) &&
                        strlen($bytes)>=$length)
                {
                        return substr($bytes,0,$length);
                }

        }
        
        function generateRandomString($length,$cryptographicallyStrong=true)
        {
                if(($randomBytes=generateRandomBytes($length+2,$cryptographicallyStrong))!==false)
                        return strtr(substr(base64_encode($randomBytes),0,$length),array('+'=>'_','/'=>'~'));
                return false;
        }
        
$dbconnection = pg_connect("host=localhost dbname=ds user=ds_user password=Apua1234"); 
        //$stamps['stamp_token'] = '';
        //$stamps['stamp_id'] = 'NULL';
        $stamps['batch_id'] = 1;
        $stamps['customer_id'] = $argv[1];
        $stamps['status'] = 'A';
        $stamps['timestamp'] = 'now()';

        for ($insert_count = 1; $insert_count <= 100; $insert_count++)
        {
            // replaced with token generated by CSecurityManager
            $stamps['stamp_token'] = generateRandomString(32, TRUE);
            // Performing SQL insert
            $res = pg_insert($dbconnection, 'ds.t_stamps_issued', $stamps);
        }
pg_close($dbconnection);

